// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsServicesAPI.DbContexts;

#nullable disable

namespace ProductsServicesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230918183725_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductsServicesAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "CategoryTest1",
                            Description = "Description about test1",
                            ImageUrl = "",
                            Name = "Test1",
                            Price = 1500.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "CategoryTest2",
                            Description = "Description about test2",
                            ImageUrl = "",
                            Name = "Test3",
                            Price = 2500.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "CategoryTest3",
                            Description = "Description about test3",
                            ImageUrl = "",
                            Name = "Test3",
                            Price = 3500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
